name: Installer
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish internal package
        run: python -m twine upload --repository github dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
